spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    schema: classpath:db/schema.sql #，每次启动程序，程序都会运行schema.sql文件，对数据库的数据操作
    url: jdbc:sqlite:code-collction.db #配置h2数据库的连接地址
    initialization-mode: always


mybatis:
  mapper-locations:
    classpath:mapping/*Mapper.xml

server:
  port: 8081
